### ISSUE TITLE
100% width page template

### ISSUE THREAD

**Issue by vibrantj** [ThemeAwesome/TotalPress#2]
Hi Thomas,
Still test driving and getting familiar with your theme. Question - would it be possible to include a 100% width page template? The full-width page template is constrained by the width set in the customizer and I don't see a way to override this setting in order to allow for content to extend beyond this. For example, having sections on a page that have full width (100% width) background images.

Keep up the good work!
John

**Comment by tsquez** [comment]
Glad you're still taking her for a spin.

Actually this was discussed a few weeks ago between myself and one other person who is helping me test and this is a feature that is going to be in TP-Primo, the premium companion plugin to TotalPress.

The feature is going to work like: this when someone sets the page template to full width there will be a metabox to change the default size of the content area to 100%, along with removing the padding. it will be in the same metabox called "**_Page Builder Options_**"

It hasn't been added yet but I can add it real quick to the plugin, test it and send you some screenshots of what it looks like.

Is there any other ideas that you think would be a good fit for the plugin?

**Comment by tsquez** [comment]
Just wanted to stop in and say I got his working with the TP-Primo plugin. I will take some screenies later and post them for you. Gotta run up to Flagstaff for a bit.

Thanks for reminding me of this 😄

**Comment by vibrantj** [comment]
Good to hear Thomas.

A few thoughts for your plugin -

The ability to easily edit the footer credits.
Header - Topbar layout option - logo next to main navigation in addition 
to above or below
A default layout (content + sidebar) on an extended width page order to 
have full-width background images with this layout

Safe travels!

John

Thomas E Vasquez wrote:

**Comment by tsquez** [comment]
Hey there,

Yes these are all part of the TP-Primo plugin

> The ability to easily edit the footer credits

 - part of TP-Primo

> Header - Topbar layout option - logo next to main navigation in addition
> to above or below

 - Part of TP-Primo

However I am not sure about the following:

> A default layout (content + sidebar) on an extended width page order to
> have full-width background images with this layout

What exactly do you mean? Did you mean something like this:

![screen shot 2017-12-21 at 11 26 10 am](https://user-images.githubusercontent.com/1976117/34264935-ad72c690-e631-11e7-99f3-a559f713a17b.png)
